# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import metri_pb2 as metri__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in metri_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MetriServiceStub(object):
    """*
    MetriService: The unified gRPC interface for the Metri Data Platform.

    Organized into three logical domains:
    1. Metadata: Registry discovery and schema exploration.
    2. Analytics: High-performance querying, batching, and semantic analysis.
    3. Operations: Transactional CRUD and bulk ingestion.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Discovery = channel.unary_unary(
                '/metri.MetriService/Discovery',
                request_serializer=metri__pb2.DiscoveryRequest.SerializeToString,
                response_deserializer=metri__pb2.DiscoveryResponse.FromString,
                _registered_method=True)
        self.Explore = channel.unary_unary(
                '/metri.MetriService/Explore',
                request_serializer=metri__pb2.ExploreRequest.SerializeToString,
                response_deserializer=metri__pb2.ExploreResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_stream(
                '/metri.MetriService/Query',
                request_serializer=metri__pb2.QueryRequest.SerializeToString,
                response_deserializer=metri__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.Transact = channel.unary_unary(
                '/metri.MetriService/Transact',
                request_serializer=metri__pb2.TransactionRequest.SerializeToString,
                response_deserializer=metri__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.BulkIngest = channel.unary_unary(
                '/metri.MetriService/BulkIngest',
                request_serializer=metri__pb2.BulkRequest.SerializeToString,
                response_deserializer=metri__pb2.BulkResponse.FromString,
                _registered_method=True)
        self.MatchRoutingRulesBatch = channel.unary_unary(
                '/metri.MetriService/MatchRoutingRulesBatch',
                request_serializer=metri__pb2.MatchRoutingRulesBatchRequest.SerializeToString,
                response_deserializer=metri__pb2.MatchRoutingRulesBatchResponse.FromString,
                _registered_method=True)


class MetriServiceServicer(object):
    """*
    MetriService: The unified gRPC interface for the Metri Data Platform.

    Organized into three logical domains:
    1. Metadata: Registry discovery and schema exploration.
    2. Analytics: High-performance querying, batching, and semantic analysis.
    3. Operations: Transactional CRUD and bulk ingestion.
    """

    def Discovery(self, request, context):
        """--- Metadata Domain ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Explore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """--- Analytics Domain ---
        The Universal Query Engine: Handles 1 query, Batch dashboards, or Multi-Series merged charts.
        Returns a stream to enable low-latency rendering of large result sets.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transact(self, request, context):
        """--- Operations Domain ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkIngest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MatchRoutingRulesBatch(self, request, context):
        """--- EDA (Event-Driven Architecture) Domain ---
        High-Performance Batch Router for O(1) Network Hopping
        Exclusive bridge for the SAM Event Router to evaluate AST logic inversely for arrays of SQS records.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetriServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Discovery': grpc.unary_unary_rpc_method_handler(
                    servicer.Discovery,
                    request_deserializer=metri__pb2.DiscoveryRequest.FromString,
                    response_serializer=metri__pb2.DiscoveryResponse.SerializeToString,
            ),
            'Explore': grpc.unary_unary_rpc_method_handler(
                    servicer.Explore,
                    request_deserializer=metri__pb2.ExploreRequest.FromString,
                    response_serializer=metri__pb2.ExploreResponse.SerializeToString,
            ),
            'Query': grpc.unary_stream_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=metri__pb2.QueryRequest.FromString,
                    response_serializer=metri__pb2.QueryResponse.SerializeToString,
            ),
            'Transact': grpc.unary_unary_rpc_method_handler(
                    servicer.Transact,
                    request_deserializer=metri__pb2.TransactionRequest.FromString,
                    response_serializer=metri__pb2.TransactionResponse.SerializeToString,
            ),
            'BulkIngest': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkIngest,
                    request_deserializer=metri__pb2.BulkRequest.FromString,
                    response_serializer=metri__pb2.BulkResponse.SerializeToString,
            ),
            'MatchRoutingRulesBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.MatchRoutingRulesBatch,
                    request_deserializer=metri__pb2.MatchRoutingRulesBatchRequest.FromString,
                    response_serializer=metri__pb2.MatchRoutingRulesBatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metri.MetriService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('metri.MetriService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MetriService(object):
    """*
    MetriService: The unified gRPC interface for the Metri Data Platform.

    Organized into three logical domains:
    1. Metadata: Registry discovery and schema exploration.
    2. Analytics: High-performance querying, batching, and semantic analysis.
    3. Operations: Transactional CRUD and bulk ingestion.
    """

    @staticmethod
    def Discovery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metri.MetriService/Discovery',
            metri__pb2.DiscoveryRequest.SerializeToString,
            metri__pb2.DiscoveryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Explore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metri.MetriService/Explore',
            metri__pb2.ExploreRequest.SerializeToString,
            metri__pb2.ExploreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/metri.MetriService/Query',
            metri__pb2.QueryRequest.SerializeToString,
            metri__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metri.MetriService/Transact',
            metri__pb2.TransactionRequest.SerializeToString,
            metri__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BulkIngest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metri.MetriService/BulkIngest',
            metri__pb2.BulkRequest.SerializeToString,
            metri__pb2.BulkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MatchRoutingRulesBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metri.MetriService/MatchRoutingRulesBatch',
            metri__pb2.MatchRoutingRulesBatchRequest.SerializeToString,
            metri__pb2.MatchRoutingRulesBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class QuotaServiceStub(object):
    """--- Quota Domain (IA Token Accounting — Fase 08) ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReserveTokens = channel.unary_unary(
                '/metri.QuotaService/ReserveTokens',
                request_serializer=metri__pb2.ReserveTokensRequest.SerializeToString,
                response_deserializer=metri__pb2.ReserveTokensResponse.FromString,
                _registered_method=True)
        self.ReconcileTokens = channel.unary_unary(
                '/metri.QuotaService/ReconcileTokens',
                request_serializer=metri__pb2.ReconcileTokensRequest.SerializeToString,
                response_deserializer=metri__pb2.ReconcileTokensResponse.FromString,
                _registered_method=True)


class QuotaServiceServicer(object):
    """--- Quota Domain (IA Token Accounting — Fase 08) ---
    """

    def ReserveTokens(self, request, context):
        """Paso 1 (Pre-flight): Verifica disponibilidad y genera reserva atómica temporal
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReconcileTokens(self, request, context):
        """Paso 4 (Post-flight): Concilia el consumo real, consolida débito y libera headroom sobrante
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuotaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReserveTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveTokens,
                    request_deserializer=metri__pb2.ReserveTokensRequest.FromString,
                    response_serializer=metri__pb2.ReserveTokensResponse.SerializeToString,
            ),
            'ReconcileTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.ReconcileTokens,
                    request_deserializer=metri__pb2.ReconcileTokensRequest.FromString,
                    response_serializer=metri__pb2.ReconcileTokensResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metri.QuotaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('metri.QuotaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuotaService(object):
    """--- Quota Domain (IA Token Accounting — Fase 08) ---
    """

    @staticmethod
    def ReserveTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metri.QuotaService/ReserveTokens',
            metri__pb2.ReserveTokensRequest.SerializeToString,
            metri__pb2.ReserveTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReconcileTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metri.QuotaService/ReconcileTokens',
            metri__pb2.ReconcileTokensRequest.SerializeToString,
            metri__pb2.ReconcileTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
