<project xmlns="http://maven.apache.org/POM/4.0.0" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.metri</groupId>
    <artifactId>metri-engine</artifactId>
    <version>1.0.0</version>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <!-- Clojure Official Maven Repository -->
    <repositories>
        <repository>
            <id>clojars</id>
            <url>https://repo.clojars.org/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.clojure</groupId>
            <artifactId>clojure</artifactId>
            <version>1.12.0</version>
        </dependency>
        <!-- OLTP Datahike Serverless -->
        <dependency>
            <groupId>io.replikativ</groupId>
            <artifactId>datahike</artifactId>
            <version>0.6.1525</version>
        </dependency>
        <dependency>
            <groupId>io.replikativ</groupId>
            <artifactId>datahike-dynamodb</artifactId>
            <version>0.1.9</version>
        </dependency>
        <!-- Cloud & Infrastructure SDKs -->
        <dependency>
            <groupId>com.cognitect.aws</groupId>
            <artifactId>api</artifactId>
            <version>0.8.692</version>
        </dependency>
        <!-- Cloud & Infrastructure SDKs -->
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>athena</artifactId>
            <version>2.25.11</version>
        </dependency>
        <!-- AWS Lambda Core -->
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-core</artifactId>
            <version>1.2.3</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-events</artifactId>
            <version>3.11.4</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- Clojure Maven Plugin para compilar Clojure en el lifecycle normal de Java -->
            <plugin>
                <groupId>com.theoryinpractise</groupId>
                <artifactId>clojure-maven-plugin</artifactId>
                <version>1.8.4</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <id>compile-clojure</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <sourceDirectories>
                        <sourceDirectory>src</sourceDirectory>
                    </sourceDirectories>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
